version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - '3333:3333'
    volumes:
      - ./api:/app
    environment:
      NODE_ENV: development
    depends_on:
      - database
      - redis
    networks:
      - zoland

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - zoland

  database:
    image: postgres:15
    container_name: postgres
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - api-psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - zoland

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - zoland

volumes:
  api-psql-data:
  redis-data:

networks:
  zoland:
    driver: bridge
